### ISSUE TITLE
  Current status of FMI development is not visible

### ISSUE THREAD

**Issue by TorstenBlochwitz** [modelica/fmi-standard.org#100]
The current status of the FMI development is not visible on one central place. The Information that next version will be 3.0 and the 3.0 Alpha Features is only visible in the "News" list of the homepage. I would propose to add a section: Current Status of FMI Development" at top of: https://fmi-standard.org/development/ and put the respective information there and update it from time to time..

**Comment by andreas-junghanns** [comment]
@t-sommer : should we point to the github project on the front page? Right now, how to contribute is hard to find.

**Comment by chrbertsch** [comment]
@TorstenBlochwitz, @andreas-junghanns and @t-sommer  : Can we close this? we have the "about", the "FAQ" which states the state of FMI3.0 development, and a link to the github project.

**Comment by TorstenBlochwitz** [comment]
I would propose to add a link to the FAQ page to the FMI homepage below the links to the current version. I propose the following text: Currently version 3.0 of FMI is in development. The planned new features are listed here (Link to FAQ page, section "What will be the new features of FMI 3.0?").

**Comment by t-sommer** [comment]
Fixed with 5fdf2c9feca299d4bb3eb789ee55dbd4053529b3
