### ISSUE TITLE
Add tool logos on FMI webpage

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard.org#120]
I propose to add logos of tools and/or tool vendors supporting FMI on the FMI webpage.
Tool vendors could upload them themselves and add the filename in https://github.com/modelica/fmi-standard.org/blob/master/_data/tools.csv.
The should implicitely agree on the usage of the logo on the website by uploading it.
Order of thel logos could be alphabetical.

**Comment by andreas-junghanns** [comment]
@chrbertsch : can we close this? Or should we try to push again? Maybe after the release of 3.0 when we have nothing else to do?

**Comment by chrbertsch** [comment]
At least for large companis, using their logo would require signing a contract, which would make things to complicated. The tools page speaks for itself.
