### ISSUE TITLE
Add public calendar for FMI events

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard.org#124]
The posts in https://fmi-standard.org/news/ are almost exclusively announcments for FMI related events. It would be convenient to have a public calendar (e.g. Google Calendar) interested people can subscribe to and get automatic updates without having to check the website and updating their private calendar.

**Comment by andreas-junghanns** [comment]
The MA backoffice somehow worked on this: I received mysterious emails. I am trying to get some answers and will post here how to find the official FMI calendar and how to get read or read/write access.

**Comment by chrbertsch** [comment]
Already online. @MABackoffice : we use https://calendar.google.com/calendar/embed?src=obe72dhd3apjmipcpmr2asehjs%40group.calendar.google.com&ctz=Europe%2FBerlin where we have access rights.

--> @t-sommer : could you please close this? (I do not have rights to do so)
