### ISSUE TITLE
Add registration to "fmi-info" mailing list again after clarifying requirements of GDPR

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard.org#127]
The registration posssibility to the mailing list "fmi-info" has been removed from the website because of concerns regarding GDPR. 
A way of fullfilling the requirments of GDPR should be implemented and a registration possibility for the mailing list be added again.

**Comment by t-sommer** [comment]
What the status here?

**Comment by chrbertsch** [comment]
We could ask MA to set up a mailing list mechanism similar to the MA Info service https://creativeconnections.us12.list-manage.com/subscribe?u=0be901f875b69817eddd7e71b&id=0cb2cf5b72.

Or we just use the MA Info service and do not maintain a separate list (would be my proposal in order to reduce administrative overhead)
Who on the MA mailing list would not be interested in FMI news :-)?
And on the other hand, the MA wants to provide a coordinated set of standards, so it makes sense to spread also information e.g. about DCP and SSP to the FMI Community.

Perhaps we should ask MA, if we could use the MA Info service also for "FMI only" announcements, like a new release, or whether this list is reserved for the quarterly MA newsletters.

**Comment by andreas-junghanns** [comment]
I like re-using the MA-info list for the reasons Christian outlined.
I will ask MartinO if he thinks this is a good idea.
I will report here in the result.

**Comment by andreas-junghanns** [comment]
Can we close this here, now that we have delegated this to Filip?

**Comment by chrbertsch** [comment]
> Can we close this here, now that we have delegated this to Filip?

I would close it once we have included the link to the registration (that is to be provided by Filip) on our website :-)

Has it been discussed in the MA Board how to proceed? Will the other MA projects join our approach?

**Comment by andreas-junghanns** [comment]
Yes, it was discussed, but the other projects where not present. So it was not much of a discussion.

**Comment by chrbertsch** [comment]
As the Modelica newletter emailing service has been extended by a FMI-info possibility, we can now re-add this to our webpage: 
https://urldefense.com/v3/__https:/creativeconnections.us12.list-manage.com/subscribe?u=0be901f875b69817eddd7e71b&id=0cb2cf5b72__;!!A4F2R9G_pg!NotBpiMT9NrfAV-nlUXEFeJaIENx_j0SSqQFl_ZTQ2cYuq0kqHdMLizJCK3W7vd_TvVBSYw$

@t-sommer Where shall we add this? On the main page, in "Contact" (very hidden), in "About" (does not match well) or in a new tab?

Once we have it, we can also create a news article

**Comment by chrbertsch** [comment]
@t-sommer : here is a permalink http://eepurl.com/dpvVdH that can be used

**Comment by chrbertsch** [comment]
Resolved with #254
