### ISSUE TITLE
Add a tool vendor column to the tools page

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard.org#128]
Currently some of the tool names on https://fmi-standard.org/tools/ contain the vendor name (e.g., "ANSYS Simplorer"), others not. In some cases, the vendors are more prominently known than the tool names, but currently not displayed in our tool list.
It would be helpful to consistently remove the vendor from the the "tool name" (e.g., "Simplorer")  and add a new column "vendor" ("ANSYS")

**Comment by andreas-junghanns** [comment]
@chrbertsch : I think this quite a task and I do not know how to do this: spelling of vendors is tricky (upper/lower case, with Inc. or PLM,...) to get right and asking vendors to fix the format might take ages to get done (we have no consistent way to contact them to ask them to get their entry fix). How would you propose the data to be cleaned up?
I suggest to leave things as they are until we completely overhaul this issue (maybe together with the logo idea).
If you agree, please close this issue.
