### ISSUE TITLE
Replacement of SVN as storage location for presentations in the literature tab

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard.org#137]
In the past, in the literature tab of the website, links to presentations at the user meeting pointed to the public part of the  fmi svn repo, e.g. https://svn.fmi-standard.org/fmi/branches/public/docs/Modelica2017/01_MAP-FMI_User_Meeting_Kickoff.pdf 
Shall this SVN be available in the future?
Where shall I store e.g. the slides of this year's "Industrial User Presentations" session at the Modelica Conference?

**Comment by t-sommer** [comment]
You could put them in fmi-standard.org/assets/documents/ and link them in pages/literature.md

**Comment by chrbertsch** [comment]
OK. 
Shall the SVN be alive for some time? Or do we have to move content that is still linked on the website somewhere else? There is also other stuff like the FMI 2.0 ME test FMUs by Martin Otter.

**Comment by t-sommer** [comment]
All links on the homepage are checked upon every build. I see no benefit in copying them if they're still available on the other server. AFAIK there are no plans to shut down the SVN any time soon.

**Comment by chrbertsch** [comment]
Closing as SVN seems to live longer ...
