### ISSUE TITLE
add advisory committee member

### ISSUE THREAD

**Issue by jbernalr** [modelica/fmi-standard.org#170]
Though this field may change in the near future, could we add (or can I do it myself?) "ITK Engineering GmbH" into the advisory committee members list to reflect what is in the fmi-design repository?:
https://github.com/modelica/fmi-design/blob/master/FMI_Members/CurrentMembers.txt
or maybe we could automate the transfer from this document into the website? 
Thanks for any infos.

**Comment by t-sommer** [comment]
Please make a PR to https://github.com/modelica/fmi-standard.org

**Comment by t-sommer** [comment]
Solved with #171
