### ISSUE TITLE
Bad/broken link to "licesenses" in CCLA document

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard.org#182]
referring to https://github.com/modelica/fmi-standard/issues/610#issuecomment-524875554

Create http://www.fmi-standard.org/licenses/ as it is referred to in the CCLA.

Andreas Junghanns: "The document is out in the wild - we need to make this link land on something, like /development.Is there such a thing as a UNIX link on the platform we live on now?"

**Comment by t-sommer** [comment]
What should be the content of this page?

**Comment by chrbertsch** [comment]
We could make it point to https://fmi-standard.org/about/

This contains all kind of of license and CCLA information: 

* _"The FMI specifications are published under the CC-BY-SA 4.0 (Creative Common Attribution-ShareAlike 4.0 International) license. Source code, such as C-header and XML-schema files, that accompany the specification documents, are provided under the 2-Clause BSD License."_

* _"All contributors have to sign the Corporate Contributor License Agreement (CCLA). Therefore, the first step is getting your company to agree and sign the CCLA. The CCLA ensures that all IP contributed to the FMI standard will be licensed to the Modelica Association (MA) which in turn will sublicense the FMI standard to tool vendors implementing it and end users using it, free of charge."_

We should change the 2nd sentence to 

* _"All contributors have to sign the Corporate Contributor License Agreement (CCLA) **(or equivalently must be corporate contributors that have signed the CLA of the Modelica Association)**. Therefore, the first step is getting your company to agree and sign the **CCLA/CLA. This** ensures that all IP contributed to the FMI standard will be licensed to the Modelica Association (MA) which in turn will sublicense the FMI standard to tool vendors implementing it and end users using it, free of charge."_

**Comment by t-sommer** [comment]
> We should change the 2nd sentence to...

@chrbertsch, please make a PR for this
