### ISSUE TITLE
Add Boeing user statement

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard.org#183]
“The FMI is a key solution to expand Model-Based Development (MBD) throughout our Supply Chain, enabling compatibility with a wide variety of environments and model types while ensuring Aerospace companies protect their IP“
-Boeing Research & Technology-Europe (BR&T-E), Boeing Commercial Airplanes (BCA)

Contact: Juan C. Mendo

Missing: Logo

**Comment by t-sommer** [comment]
I've removed the acronyms in brackets because they only appear once and break the layout.

**Comment by chrbertsch** [comment]
We have to temporarily remove the Boeing statement, until we get consent for the logo usage (cf. email from Mendo)
Please re-open the issue.
