### ISSUE TITLE
Add privacy statement for "FMU Check"

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard.org#203]
@chrbertsch, since you brought this up, can you propose a text?

**Comment by chrbertsch** [comment]
IANAL, but here are some proposals: 

This service uses fmpy to validate the modeldescription.xml file of an FMU against the FMI xsd schema and the FMI standard. By selecting an FMU you consent to  upload it to the XXX Cloudservice hosted by company YYY. The FMU will afterwards be deleted, i.e., it will not be permanently stored.
No one else than you will receive the validation results.

THIS SERVICE IS PROVIDED  "AS IS" AND ANY WARRANTIES ARE DISCLAIMED.
No warrenty or guarantee is provided for the correctness of the results.
