### ISSUE TITLE
Online checker stops while testing FMU

### ISSUE THREAD

**Issue by ghorwin** [modelica/fmi-standard.org#210]
Steps to reproduce: upload attached FMU to online FMU compliance checker. Progress bar shows that file is being uploaded, but stops after the progress bar has reached about half of the screen width. May just be related to the file size. Uploading the same FMU built in "small-release-size" mode, the checker works.

(Rename .zip to .fmu before uploading)
[CollectorRohr_linux64.zip](https://github.com/modelica/fmi-standard.org/files/3878816/CollectorRohr_linux64.zip)

**Comment by t-sommer** [comment]
The problem was the 30 s timeout of the service worker rather than the file size. I've changed it to 300 s.
