### ISSUE TITLE
Unclear on pandapower support in tools page

### ISSUE THREAD

**Issue by thisiswhereitype** [modelica/fmi-standard.org#292]
Pandapower tool does not directly support FMI, but does via various third party tools however this is not clear.

PR #234 adds pandapower 

But this is not clear according to this: [pandapower issue 777](https://github.com/e2nIEE/pandapower/issues/777)

[The comment](https://github.com/e2nIEE/pandapower/issues/777#issuecomment-644664491) points to another repository:
https://framagit.org/Adrien.Gougeon/pandapower-fmu

Other results which appear 3rd party with respect to Pandapower:

[https://fmi-for-power-system.readthedocs.io/en/latest/05_available_fmus.html](https://fmi-for-power-system.readthedocs.io/en/latest/05_available_fmus.html)
[https://github.com/AIT-IES/pandapowerFMU](https://github.com/AIT-IES/pandapowerFMU)

I am not using this, but it is unclear when first reaching the page.
Can you alter to indicate pandapower-via-X?

**Comment by chrbertsch** [comment]
@AdrienGougeon : if the  FMU export from pandapower is not official but provided from https://framagit.org/Adrien.Gougeon/pandapower-fmu, I suggest that you rename the entry  in the list https://fmi-standard.org/tools/ from "pandapower" to "pandapower-fmu" and link to your github repo

Are you in connection with the developers of https://github.com/AIT-IES/pandapowerFMU?
Perhaps you should avoid naming confusion.

**Comment by adrgougeon** [comment]
@chrbertsch: you are right, I made a pull request to rename the tool and changed to link

I am not in connection with the developers of https://github.com/AIT-IES/pandapowerFMU

**Comment by andreas-junghanns** [comment]
I see no prending PR for this, so either nobody cares are this was already fixed - closing.
