### ISSUE TITLE
Add link to latest tagged version of FMI3.0(alpha, beta, RC) 

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard.org#293]

**Comment by andreas-junghanns** [comment]
Who can create a PR?

**Comment by t-sommer** [comment]
There is [a news post with a link to the (pre-)releases](https://fmi-standard.org/news/2021/04/21/fmi3.0beta.1-prerelease.html) on the front page. Do we need yet another link?

**Comment by chrbertsch** [comment]
OK, the news post should be enough
