### ISSUE TITLE
Reduce Whitespace

### ISSUE THREAD

**Issue by xogeny** [modelica/fmi-standard.org#30]
The current CSS (IIRC) uses media queries to determine screen size and then picks a fixed width  based on width ranges.  Using fixed widths as the advantage that it only a few specific widths are possible and so layout can be verified for each of those potential values.

One downside of fixed width layout is that you can wind up with significant amounts of white space in the left and right margins.  Using fixed *margins* can result in greater utilization of the screen space but will mean that the width can take on an effectively infinite number of possible values.  So care must be taken that the responsive design elements are robust in the face of so many possible widths.

@andreas-junghanns, in light of these comments do you want to push for the user of fixed margins (less overall whitespace)?  I'm not trying to scare you off here, I'm just stating what I see as the pros and cons so other can comment as well if they see any issues with my analysis.

**Comment by andreas-junghanns** [comment]
I think we should wait until we run into problems with the two-column mode (read: run out of space). Once we get to that point, we can discuss margins again.

**Comment by t-sommer** [comment]
@xogeny, is this still an issue with the new Bootstrap based layout?
