### ISSUE TITLE
Add Link to FMI Trademark usage in FAQ

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard.org#306]
Currently I do not find a link to https://svn.modelica.org/fmi/branches/public/docs/Trademark%20Guidelines%20for%20the%20Use%20of%20the%20FMI%20Trademark%20V1.0.pdf  on our website.

**Comment by sjoelund** [comment]
For sure do not link to that anywhere and save that repository somewhere if you need it. It's going offline in a few days.

**Comment by andreas-junghanns** [comment]
The source of the file is in [https://github.com/modelica/fmi-design/tree/master/FMI_Trademark]. If we cannot link that, we need a copy in the fmi-standard.org repo.

**Comment by sjoelund** [comment]
That repository is private, so I guess you would need it in fmi-standard.org. But it seems like a rather simple document. I think you would want to put it was markdown so it's just a normal webpage.

**Comment by andreas-junghanns** [comment]
solved with #329
