### ISSUE TITLE
Links to FMI 1.0.1 standard Zip an PDF files broken

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard.org#343]
The links on https://fmi-standard.org/downloads/ for the download of FMI 1.0.1 are broken (the point the the old SVN server).

The PDFs are located here: https://github.com/modelica/fmi-design/tree/master/FMI_1.0.1, but have we stored anywhere the "complete package" Zip Files? @sjoelund could you perhaps restore them from the SVN backup? Thanks

(in fact, perhaps it is a good sign that nobody complained about this: FMI 1.0 seems to become obsolete :-) )

**Comment by sjoelund** [comment]
[FMI_for_CoSimulation_v1.0.1.pdf](https://github.com/modelica/fmi-standard.org/files/7631505/FMI_for_CoSimulation_v1.0.1.pdf)
[FMI_for_CoSimulation_v1.0.1.zip](https://github.com/modelica/fmi-standard.org/files/7631506/FMI_for_CoSimulation_v1.0.1.zip)
[FMI_for_CoSimulation_v1.0.pdf](https://github.com/modelica/fmi-standard.org/files/7631507/FMI_for_CoSimulation_v1.0.pdf)
[FMI_for_CoSimulation_v1.0.zip](https://github.com/modelica/fmi-standard.org/files/7631508/FMI_for_CoSimulation_v1.0.zip)
[FMI_for_ModelExchange_v1.0.1.pdf](https://github.com/modelica/fmi-standard.org/files/7631509/FMI_for_ModelExchange_v1.0.1.pdf)
[FMI_for_ModelExchange_v1.0.1.zip](https://github.com/modelica/fmi-standard.org/files/7631510/FMI_for_ModelExchange_v1.0.1.zip)
[FMI_for_ModelExchange_v1.0.pdf](https://github.com/modelica/fmi-standard.org/files/7631511/FMI_for_ModelExchange_v1.0.pdf)
[FMI_for_ModelExchange_v1.0.zip](https://github.com/modelica/fmi-standard.org/files/7631512/FMI_for_ModelExchange_v1.0.zip)
[FMI_for_PLM_v1.0.pdf](https://github.com/modelica/fmi-standard.org/files/7631513/FMI_for_PLM_v1.0.pdf)
[FMI_for_PLM_v1.0.zip](https://github.com/modelica/fmi-standard.org/files/7631514/FMI_for_PLM_v1.0.zip)
[FMI_for_ModelExchange_and_CoSimulation_v2.0.pdf](https://github.com/modelica/fmi-standard.org/files/7631516/FMI_for_ModelExchange_and_CoSimulation_v2.0.pdf)
[FMI_for_ModelExchange_and_CoSimulation_v2.0.zip](https://github.com/modelica/fmi-standard.org/files/7631518/FMI_for_ModelExchange_and_CoSimulation_v2.0.zip)
