### ISSUE TITLE
Add "how can I list a new tool or update tool information?" to tools page

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard.org#410]
Add a link to https://github.com/modelica/fmi-standard.org/blob/main/CONTRIBUTING.md#updating-the-tools-list on  https://fmi-standard.org/tools/

**Comment by andreas-junghanns** [comment]
I think Contributing.md should be linked to directly from /about, at least.
I personally think this could also be another tab in the headline of the pages - as we seek contributions, right?
