### ISSUE TITLE
Add link to download FMI 2 Download

### ISSUE THREAD

**Issue by JohannesUl** [modelica/fmi-standard.org#429]
Hi,

even though FMI 3.0 is released now I would appreciate a link to download the FMI 2 standard and package on the website. 

Best,
Johannes

**Comment by chrbertsch** [comment]
Sure :-) 
![grafik](https://user-images.githubusercontent.com/16363372/186905966-d837b3be-bbce-4def-97dd-ea4f254ba92a.png)

**Comment by JohannesUl** [comment]
Thanks. Not obvious to find though. ;-)
