### ISSUE TITLE
CCLA missing (link dos not work)

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard.org#431]
The Link to the CCLA does not work. 
https://github.com/modelica/fmi-standard.org/tree/main/assets/FMI_CCLA_v1.0_2016_06_21.pdf
Was this removed during the switch to Huge?

Where are such files supposed to reside? in /assets or static/assets?

**Comment by t-sommer** [comment]
Are you looking for https://github.com/modelica/fmi-standard/blob/main/FMI_CCLA.adoc?

**Comment by chrbertsch** [comment]
I am looking at the link to the CCLA in https://fmi-standard.org/about/ that does not work, and which should link to printable (PDF) version of the CCLA, not to the adoc.
