### ISSUE TITLE
Make sidebar 

### ISSUE THREAD

**Issue by xogeny** [modelica/fmi-standard.org#5]
The sidebar would be more attractive if it had rounded corners and perhaps a bit of shadow.  Will you accept a PR for this?

**Comment by andreas-junghanns** [comment]
Rounded edges as the tools buttons have? Sure, that sounds reasonable. But again: What about the Word and PowerPoint templates? Should those not be changed the same way to keep things identical?

I think we should discuss the general approach to changing styling in a larger group as we accepted the proposal from the agency.

**Comment by xogeny** [comment]
I don't know anything about the Word or PowerPoint templates.  Note that the rounded edges were already merged into the web site.
