### ISSUE TITLE
Missing right border if only 1.0 is framed

### ISSUE THREAD

**Issue by beutlich** [modelica/fmi-standard.org#54]
It looks like the right border is missing if only 1.0 is framed.

![grafik](https://user-images.githubusercontent.com/14896695/45708542-fc210d80-bb81-11e8-8a6f-08c3d6a289a6.png)

**Comment by t-sommer** [comment]
The outlines are provided by the [Bootstrap Button Groups](https://getbootstrap.com/docs/4.1/components/button-group/). The border comes from the right button.

**Comment by beutlich** [comment]
OK, we simply must avoid tools with planned 1.0 support but unavailable 2.0 support then. :smiley:
