### ISSUE TITLE
Cannot use filter for Tools.

### ISSUE THREAD

**Issue by benben233** [modelica/fmi-standard.org#540]
We cannot use the filter in [Tools](https://fmi-standard.org/tools/). Clicked it and nothing happened.
![image](https://github.com/modelica/fmi-standard/assets/15977874/ae9b27cf-e38c-4a35-afe0-e306eea6b19a)

**Comment by benben233** [comment]
> Can you please provide steps to reproduce the problem?

Just click the Tools. And click the filters. And nothing happened.  You can see the Error, maybe because I use proxy. Maybe it is a bug from Vue3.

**Comment by benben233** [comment]
And I use another device, another network, and ask my colleague to open it **without proxy**. But the same error, it is strange.

**Comment by t-sommer** [comment]
This should be fixed with f25c0438d9ad4a3f5fed01404941839c782abfff. Please reopen if the problem persists.
