### ISSUE TITLE
Add a note to the asciidoc / html version of the FMI Standard, the released PDF version is the valid version

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard.org#57]
In order to avoid ambiguity in case of typos, we should add a note the asciidoc version of the FMI 2.0 standard, that the release PDF version of the standard is the valid one in case of differences.

**Comment by t-sommer** [comment]
@chrbertsch, can you please make a PR once the Trac tickets are migrated?

**Comment by chrbertsch** [comment]
OK. 
@beutlich : Are you already working on the migration of tickets or when is this planned? Thanks!

**Comment by beutlich** [comment]
There are only 6 Trac tickets to migrate here. We'll probably will not synchronize the tickte numbers then.

https://trac.fmi-standard.org/query?status=assigned&status=closed&status=new&status=reopened&component=website&order=priority

**Comment by t-sommer** [comment]
@chrbertsch, do you want to add the note to the homepage (this repo) or the fmi-standard itself?

**Comment by chrbertsch** [comment]
I agree.

**Comment by t-sommer** [comment]
Maybe we should not tag / publish the 2.0 HTML version and start with 2.0.1 to avoid confusion in the first place.

**Comment by t-sommer** [comment]
We can still regularly publish the development version as 2.0.1-snapshot on the website to give people the chance to review it w/o installing any tools.

**Comment by andreas-junghanns** [comment]
Sure, 2.0 is not really important. Important is how we move forward.

**Comment by t-sommer** [comment]
Resolved with modelica/fmi-standard@15e4780822b312f0bca90a6c90d84c77722fd32e

**Comment by chrbertsch** [comment]
On https://fmi-standard.org/downloads/ there is still a link to https://fmi-standard.org/docs/2.0.1-develop/.  It is not mentioned, that this is an unreleased version. 
It is not clear to me from which sources this is created. (From the branch support/v2.0.1?)
We should not link to this unreleased version  from https://fmi-standard.org/downloads/ , but perhaps from https://fmi-standard.org/develop
