### ISSUE TITLE
Improve tool filter on import / export and CS / ME

### ISSUE THREAD

**Issue by beutlich** [modelica/fmi-standard.org#59]
Is there any chance to filter the tools list to only show importers / exporters and CS / ME tools?

**Comment by t-sommer** [comment]
We're trying to keep the filters as simple as possible. It should allow users to reduce the list to fit on one page.

**Comment by beutlich** [comment]
Well, I'd leave this open for discussion. Filtering on the columns is definitely nice to have, otherwise you are totally lost on that long list.
