### ISSUE TITLE
Invalid https links

### ISSUE THREAD

**Issue by beutlich** [modelica/fmi-standard.org#65]
The change in #62 changed many links into invalid ones, e.g., https://www.pysimulator.org or https://www.virtualmotion.co.kr/en/index.do or https://www.xmodsoftware.com/.

**Comment by t-sommer** [comment]
The [automatic check](https://github.com/modelica/fmi-standard.org/blob/master/.travis.yml#L9) reported no problems. I'll look into it.

**Comment by t-sommer** [comment]
The above websites serve content via https but use invalid certificates.

**Comment by pmai** [comment]
And at least https://www.pysimulator.org/ is now a parked domain, so invalid in any case.

**Comment by t-sommer** [comment]
It's up to the webmasters of the respective websites to use valid SSL certificates (e.g. from https://letsencrypt.org/).
