### ISSUE TITLE
Add a "who's using FMI" section

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard.org#70]
It would be nice to have a section with logos of companies using FMI on the start page (similar to GitHub's website, see below) maybe even with a quote ("We use FMI at XXX..."). Three or four "big names" from each industry (automotive, aerospace, industrial equipment, medical, research, ...) would be great.

<img width="908" alt="screenshot 2018-10-01 19 57 39" src="https://user-images.githubusercontent.com/2453858/46306902-cfbfb500-c5b5-11e8-9440-65886e83460e.png">

**Comment by chrbertsch** [comment]
How to get approval from the companies to get listed there?
How does github do it? (github is different as it is commercial. So I expect the companies  
How do open source projects like jupyter do it?
![grafik](https://user-images.githubusercontent.com/16363372/46332639-96229480-c61d-11e8-9d9b-ea3fc7abb479.png)

**Comment by t-sommer** [comment]
I would expect that a lot of companies would be proud to be listed on the website. We could approach them directly as Modelica Association asking whether it's ok to use their logo.

@chrbertsch How about BOSCH e.g.?

**Comment by chrbertsch** [comment]
I support the idea and will clarify how our company handles this.

**Comment by edrenth** [comment]
Agree with the idea and hope to get back in due course. But, we will need a few before publishing. Just one or two may give a negative impression.

**Comment by a-marion** [comment]
That is a great idea. That would help understand the use of the FMI.

**Comment by chrbertsch** [comment]
Regarding statements of companies: We could cite from https://itea3.org/project/impact-story/modelisar-impact-story.html or link it.

**Comment by t-sommer** [comment]
@edrenth with Haldex

<img width="1333" alt="screenshot 2018-11-08 00 02 58" src="https://user-images.githubusercontent.com/2453858/48166743-ca0e6b00-e2e9-11e8-99a9-fb737b0fe907.png">

**Comment by chrbertsch** [comment]
Fine for Bosch.  An agreement regarding the usage of the Bosch Logo on the FMI Website was sent to Martin Otter as MA Chairman for signature.
How shall we go on to get further companies? @pmai :  could you ask Prostep member Companies to back this (Mr Rude organized in the past a GAAG statement to support FMI from leading OEMs) 
@hubertus65: Could you use your contacts to companies to back this?
