### ISSUE TITLE
Use only official FMI logo (including colours)

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard.org#71]
In order to protect our Trademark, we must use the official colour scheme of our logo and should not use another as currently in the title bar.
![grafik](https://user-images.githubusercontent.com/16363372/46333010-f2d27f00-c61e-11e8-8828-72720eb28950.png)
Citing https://igerent.com/colors-trademarks-claim-or-not-claim : 

> In most countries if you require to show use of the trademark, for example to defend your trademark registration against cancellation action based on lack of use, the trademark authority will require the use to be for the trademark exactly as it was registered.

**Comment by t-sommer** [comment]
From the [FMI/FMU Logo and FMI Office Templates Terms and Conditions](https://svn.fmi-standard.org/fmi/branches/public/FMILogo-License_v5.pdf):

> You are allowed to:
>  [...] Convert the logos to greyscale versions if necessary.

**Comment by chrbertsch** [comment]
IMHO we should delete this. (However, nobody will make a fuss about printing the logo in black and white.)
But most important is, that we as the trademark owner use our logo consistently, fulfilling our obligation to protect our trademark.

**Comment by chrbertsch** [comment]
I got in priniciple the OK to use the Bosch logo for this purpose.
What I would need for final OK is a draft of the Website with the Bosch logo on it,  and someone signing the Bosch conditions for using our logo (@andreas-junghanns  or @MartinOtter  for the MA?)

**Comment by andreas-junghanns** [comment]
I cannot sign for the MA - only Martin can.

**Comment by chrbertsch** [comment]
The proposal https://user-images.githubusercontent.com/2453858/48161385-b14a8900-e2da-11e8-8fa4-8370ed03d6d1.png for the website is fine for Bosch. It can be published after signature of Martin of the usage agreement for our logo.

**Comment by beutlich** [comment]
Discussion at the [MA board meeting](https://trac.modelica.org/Modelica/browser/ModelicaDesign/trunk/Modelica-Association/Board-Meetings/2019-09-03-Web-Meeting/_2019-09-03-Minutes.docx) from 2019-09-03:

> Proposal: In exceptional cases the logo can be inverted (e.g. logo on a dark scheme of a navigation bar on a web page). If a logo is inverted, then all logo colors must be changed to "white".
> Seems to be agreement.
