### ISSUE TITLE
Remove subdomain "preview.fmi-standard.org"

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard.org#74]

**Comment by t-sommer** [comment]
- [x] branch "dynamic" has been removed

**Comment by t-sommer** [comment]
There seems to be a [CNAME record](https://help.github.com/articles/setting-up-a-custom-subdomain/) in place that redirects preview.fmi-standard.org to angry-euclid-d015f6.netlify.com:

```
$ nslookup preview.fmi-standard.org

Non-authoritative answer:
preview.fmi-standard.org	canonical name = angry-euclid-d015f6.netlify.com.
Name:	angry-euclid-d015f6.netlify.com
Address: 142.93.108.123
```

@adeas31, can you take care of fixing this?

**Comment by sjoelund** [comment]
@adeas31 does not have access to the DNS. I have removed the CNAME

**Comment by t-sommer** [comment]
Thanks!
