### ISSUE TITLE
Links within the tools table always point to win64 cross checks

### ISSUE THREAD

**Issue by APillekeit** [modelica/fmi-standard.org#99]
Hi,

The links on the tools page doesn't seem to be updated properly.
If one clicks on the e.g. 2.0 symbol for a tool in the table the user is always directed towards: https://fmi-standard.org/cross-check/fmi2-cs-win64/
It seems to be the case that the win64 cross checks are always linked. Even though if win64 is not specified as a supported platform e.g. for dSPACE SCALEXIO

Regards
Andreas

**Comment by t-sommer** [comment]
Currently all buttons in the tools list link to the respective results for `win64` because it's the most popular platform (that is supported by all tools except SCALEXIO and TargetLink). A PR that implements a more sophisticated solution is welcome!

**Comment by APillekeit** [comment]
I understand that win64 is the most popular platform. That is most likly true, but please note that the initial script for creating the website activated the win64 support for all platforms by default, even for SCALEXIO and other HIL platforms. Thus the complete support for win64 is to some extend a tooling issue of the FMI cross check website. A PR that fixes the link issue would be great. I also encourage the tool vendors to update the information in tool.csv related to their tools.

**Comment by andreas-junghanns** [comment]
abandoned ticket, closing.
